version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "US/Pacific"
    groups:
      rust-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "US/Pacific"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/icechunk-js"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "US/Pacific"
    groups:
      js-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/icechunk-js/examples/node-cli"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "npm"
    directory: "/icechunk-js/examples/react-wasm"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
