version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-latest"

  jobs:
    install:
      - which mamba
      - cd icechunk-python && maturin build && pip install "$(ls ../target/wheels/*.whl | head -n 1)" && pip install --group docs && maturin develop
      - mamba list
      - cd icechunk-python && maturin develop && cd docs

conda:
  environment: docs/doc-env.yml
mkdocs:
  configuration: docs/mkdocs.yml
