version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3"

  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
    post_install:
      # VIRTUAL_ENV needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --directory docs
      - pwd && ls

mkdocs:
  configuration: docs/mkdocs.yml
