# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.1"
manifest_format = "2.0"
project_hash = "20654aef53cadae0903672bbaa1d3c93476e2213"

[[deps.IceChunk]]
path = "IceChunk"
uuid = "04a3a897-0ca6-45fd-9ad3-92ea41c812af"
version = "1.0.0-DEV"
