/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Repository {
  static create(storage: JsStorage, config?: RepositoryConfig | undefined | null, specVersion?: number | undefined | null): Promise<Repository>
  static open(storage: JsStorage, config?: RepositoryConfig | undefined | null): Promise<Repository>
  static openOrCreate(storage: JsStorage, config?: RepositoryConfig | undefined | null, specVersion?: number | undefined | null): Promise<Repository>
  static exists(storage: JsStorage): Promise<boolean>
  readonlySession(options?: ReadonlySessionOptions | undefined | null): Promise<JsSession>
  writableSession(branch: string): Promise<JsSession>
  listBranches(): Promise<Array<string>>
  createBranch(name: string, snapshotId: string): Promise<void>
  listTags(): Promise<Array<string>>
  createTag(name: string, snapshotId: string): Promise<void>
  lookupManifestFiles(snapshotId: string): Promise<Array<JsManifestFileInfo>>
}
export type JsRepository = Repository

export declare class Session {
  get readOnly(): boolean
  get snapshotId(): string
  get branch(): string | null
  get hasUncommittedChanges(): boolean
  get store(): JsStore
  commit(message: string): Promise<string>
  discardChanges(): Promise<void>
}
export type JsSession = Session

export declare class Storage {
  static newInMemory(): Promise<Storage>
  static newLocalFilesystem(path: string): Promise<Storage>
  static newS3(bucket: string, prefix?: string | undefined | null, credentials?: S3Credentials | undefined | null, options?: S3Options | undefined | null): Storage
  static newR2(bucket?: string | undefined | null, prefix?: string | undefined | null, accountId?: string | undefined | null, credentials?: S3Credentials | undefined | null, options?: S3Options | undefined | null): Storage
  static newTigris(bucket: string, prefix?: string | undefined | null, credentials?: S3Credentials | undefined | null, options?: S3Options | undefined | null, useWeakConsistency?: boolean | undefined | null): Storage
  static newS3ObjectStore(bucket: string, prefix?: string | undefined | null, credentials?: S3Credentials | undefined | null, options?: S3Options | undefined | null): Promise<Storage>
  static newGcs(bucket: string, prefix?: string | undefined | null, credentials?: GcsCredentials | undefined | null, config?: Record<string, string> | undefined | null): Storage
  static newAzureBlob(account: string, container: string, prefix?: string | undefined | null, credentials?: AzureCredentials | undefined | null, config?: Record<string, string> | undefined | null): Promise<Storage>
  static newHttp(baseUrl: string, config?: Record<string, string> | undefined | null): Storage
}
export type JsStorage = Storage

export declare class Store {
  get(key: string): Promise<Buffer | null>
  getRange(key: string, offset: number, length?: number | undefined | null): Promise<Buffer | null>
  set(key: string, value: Buffer): Promise<void>
  exists(key: string): Promise<boolean>
  delete(key: string): Promise<void>
  list(): Promise<Array<string>>
  listPrefix(prefix: string): Promise<Array<string>>
  listDir(prefix: string): Promise<Array<string>>
  get supportsWrites(): boolean
  get supportsDeletes(): boolean
  get supportsListing(): boolean
}
export type JsStore = Store

/** Azure credentials */
export type AzureCredentials =
  | { type: 'FromEnv' }
  | { type: 'Static', field0: AzureStaticCredentials }

/** Azure static credentials */
export type AzureStaticCredentials =
  | { type: 'AccessKey', field0: string }
  | { type: 'SasToken', field0: string }
  | { type: 'BearerToken', field0: string }

/** Caching configuration */
export interface CachingConfig {
  numSnapshotNodes?: number
  numChunkRefs?: number
  numTransactionChanges?: number
  numBytesAttributes?: number
  numBytesChunks?: number
}

/** Compression algorithm */
export declare const enum CompressionAlgorithm {
  Zstd = 0
}

/** Compression configuration */
export interface CompressionConfig {
  algorithm?: CompressionAlgorithm
  level?: number
}

/** GCS credentials */
export type GcsCredentials =
  | { type: 'Anonymous' }
  | { type: 'FromEnv' }
  | { type: 'Static', field0: GcsStaticCredentials }

/** GCS static credentials */
export type GcsStaticCredentials =
  | { type: 'ServiceAccount', field0: string }
  | { type: 'ServiceAccountKey', field0: string }
  | { type: 'ApplicationCredentials', field0: string }
  | { type: 'BearerToken', field0: string }

export interface ManifestFileInfo {
  id: string
  sizeBytes: number
  numChunkRefs: number
}

export interface ReadonlySessionOptions {
  branch?: string
  tag?: string
  snapshotId?: string
}

/**
 * Repository configuration
 *
 * The `manifest` field accepts a JSON object matching the serde serialization
 * of `ManifestConfig`. Example:
 * ```js
 * {
 *   manifest: {
 *     preload: {
 *       max_total_refs: 1000,
 *       preload_if: { true: null },
 *       max_arrays_to_scan: 10
 *     },
 *     splitting: {
 *       split_sizes: [
 *         [{ path_matches: { regex: ".*" } }, [{ condition: "any", num_chunks: 100 }]]
 *       ]
 *     }
 *   }
 * }
 * ```
 */
export interface RepositoryConfig {
  inlineChunkThresholdBytes?: number
  getPartialValuesConcurrency?: number
  compression?: CompressionConfig
  maxConcurrentRequests?: number
  caching?: CachingConfig
  storage?: StorageSettings
  /**
   * Manifest configuration, passed as a JSON-compatible object.
   * The object is deserialized using serde, matching the Rust ManifestConfig structure.
   */
  manifest?: any
}

/** S3 credentials */
export type S3Credentials =
  | { type: 'FromEnv' }
  | { type: 'Anonymous' }
  | { type: 'Static', field0: S3StaticCredentials }

/** S3 options */
export interface S3Options {
  region?: string
  endpointUrl?: string
  allowHttp?: boolean
  anonymous?: boolean
  forcePathStyle?: boolean
  networkStreamTimeoutSeconds?: number
  requesterPays?: boolean
}

/** S3 static credentials */
export interface S3StaticCredentials {
  accessKeyId: string
  secretAccessKey: string
  sessionToken?: string
}

/** Storage concurrency settings */
export interface StorageConcurrencySettings {
  maxConcurrentRequestsForObject?: number
  idealConcurrentRequestSize?: number
}

/** Storage retries settings */
export interface StorageRetriesSettings {
  maxTries?: number
  initialBackoffMs?: number
  maxBackoffMs?: number
}

/** Storage settings */
export interface StorageSettings {
  concurrency?: StorageConcurrencySettings
  retries?: StorageRetriesSettings
  unsafeUseConditionalUpdate?: boolean
  unsafeUseConditionalCreate?: boolean
  unsafeUseMetadata?: boolean
  storageClass?: string
  metadataStorageClass?: string
  chunksStorageClass?: string
  minimumSizeForMultipartUpload?: number
}
