"""Property-based round-trip test for `icechunk.from_zarr`.

For each random zarr v3 hierarchy generated by `icechunk.testing.trees`,
materialize it into an obstore-backed source store, ingest it into a
fresh in-memory icechunk repo via `from_zarr`, and assert:

1. The destination's key set matches the source's.
2. Every key's bytes round-trip exactly.
3. The zarr API round-trips: every group's attrs and every array's
   shape, dtype, chunks, attrs, fill_value, and contents match.
"""

from __future__ import annotations

import asyncio
from typing import cast

import numpy as np
import obstore.store
import pytest
from hypothesis import HealthCheck, given, settings

import icechunk
import zarr
import zarr.storage
from icechunk.testing.models import ArrayNode, GroupNode
from icechunk.testing.trees import trees
from zarr.core.buffer import default_buffer_prototype

_PROTOTYPE = default_buffer_prototype()


async def _all_keys(store: zarr.abc.store.Store) -> set[str]:
    return {k async for k in store.list_prefix("")}


async def _key_bytes(store: zarr.abc.store.Store, key: str) -> bytes:
    buf = await store.get(key, prototype=_PROTOTYPE)
    assert buf is not None, f"missing key in store: {key!r}"
    return buf.to_bytes()


@given(tree=trees())
@settings(
    max_examples=25,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
)
def test_ingest_roundtrip(
    tmp_path_factory: pytest.TempPathFactory, tree: GroupNode
) -> None:
    src_dir = tmp_path_factory.mktemp("ingest_src")
    src_raw = obstore.store.LocalStore(str(src_dir))
    src = zarr.storage.ObjectStore(src_raw)
    tree.materialize(src)

    repo = icechunk.Repository.create(icechunk.in_memory_storage())
    icechunk.from_zarr(src, repo, message="hypothesis ingest")

    sess = repo.readonly_session(branch="main")
    dst = sess.store

    asyncio.run(_assert_byte_identical(src, dst))
    _assert_zarr_api_matches(src, dst, tree)


async def _assert_byte_identical(
    src: zarr.abc.store.Store, dst: zarr.abc.store.Store
) -> None:
    src_keys = await _all_keys(src)
    dst_keys = await _all_keys(dst)
    missing = src_keys - dst_keys
    extra = dst_keys - src_keys
    assert not missing, f"keys missing from dst: {sorted(missing)}"
    assert not extra, f"unexpected keys in dst: {sorted(extra)}"
    for key in src_keys:
        sb = await _key_bytes(src, key)
        db = await _key_bytes(dst, key)
        assert sb == db, f"byte mismatch at {key!r}"


def _assert_zarr_api_matches(
    src: zarr.abc.store.Store,
    dst: zarr.abc.store.Store,
    tree: GroupNode,
) -> None:
    src_root = zarr.open_group(src, mode="r")
    dst_root = zarr.open_group(dst, mode="r")
    assert dict(dst_root.attrs) == dict(src_root.attrs), "root attrs differ"

    for path, node in tree.walk():
        if isinstance(node, ArrayNode):
            src_arr = cast(zarr.Array, src_root[path])
            dst_arr = cast(zarr.Array, dst_root[path])
            assert dst_arr.shape == src_arr.shape, f"shape mismatch at {path}"
            assert dst_arr.dtype == src_arr.dtype, f"dtype mismatch at {path}"
            assert dst_arr.chunks == src_arr.chunks, f"chunks mismatch at {path}"
            assert dict(dst_arr.attrs) == dict(src_arr.attrs), f"attrs mismatch at {path}"
            assert _fill_eq(dst_arr.fill_value, src_arr.fill_value), (
                f"fill_value mismatch at {path}"
            )
            if node.data is not None:
                np.testing.assert_array_equal(
                    np.asarray(dst_arr[:]),
                    np.asarray(src_arr[:]),
                    err_msg=f"data mismatch at {path}",
                )
        else:  # GroupNode
            assert dict(dst_root[path].attrs) == dict(src_root[path].attrs), (
                f"group attrs mismatch at {path}"
            )


def _fill_eq(a: object, b: object) -> bool:
    """NaN-aware equality for fill_values."""
    try:
        if np.isnan(a) and np.isnan(b):  # type: ignore[arg-type]
            return True
    except (TypeError, ValueError):
        pass
    return a == b
