version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-latest"

  jobs:
     install:
      - which mamba
      - cd icechunk-python && maturin build && pip install ../target/wheels/*.whl && cd ../docs
      # - cd icechunk-python && maturin develop && cd ../docs


conda:
  environment: docs/doc-env.yml
mkdocs:
  configuration: docs/mkdocs.yml
