version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniconda3-4.7"

  jobs:
     pre_create_environment:
       - conda update --yes --quiet --name=base --channel=defaults conda

conda:
  environment: docs/doc-env.yml
  jobs:
    # post_create_environment:
    install:
      - cd ../icechunk-python && maturin develop && cd ../docs

mkdocs:
  configuration: docs/mkdocs.yml
