version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3"

  jobs:
    post_create_environment:
      # Install poetry
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      # Install deps and build using poetry
      - . "$READTHEDOCS_VIRTUALENV_PATH/bin/activate" && cd docs && poetry install

mkdocs:
  configuration: docs/mkdocs.yml
