repos:
  s3repo:
    location:
      bucket: testbucket
      prefix: testfolder/
    object_store_config: !s3
      region: eu-west-1
      endpoint_url: null
      anonymous: false
      allow_http: false
    credentials: !S3 FromEnv
    config:
      inline_chunk_threshold_bytes: null
      unsafe_overwrite_refs: null
      get_partial_values_concurrency: null
      compression: null
      caching: null
      storage: null
      virtual_chunk_containers: null
      manifest: null
  localrepo:
    location: null
    object_store_config: !local_file_system testfolder
    credentials: None
    config:
      inline_chunk_threshold_bytes: null
      unsafe_overwrite_refs: null
      get_partial_values_concurrency: null
      compression: null
      caching: null
      storage: null
      virtual_chunk_containers: null
      manifest: null
