name: CI Coordinator

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:
  schedule:
    # Three times a day for integration tests
    - cron: '33 3,10,15 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # Primary build (Ubuntu x86) - most important for testing
  build_primary:
    name: Build Primary
    uses: ./.github/workflows/shared-build.yaml
    with:
      rust_channel: '1.89.0'
      upload_rust_artifacts: true
      upload_python_wheels: true
      target: x86_64
      runner: ubuntu-latest

  # Core tests using primary build
  test_primary:
    name: Test Primary
    needs: [build_primary]
    uses: ./.github/workflows/rust-testing-safe.yaml
    with:
      target: x86_64
      runner: ubuntu-latest
      include_docker_tests: true

  # Python tests
  python_tests:
    name: Python Tests
    needs: [build_primary]
    uses: ./.github/workflows/python-testing.yaml
    with:
      target: x86_64

  # Integration tests with cloud credentials
  test_integration:
    name: Test Integration
    needs: [build_primary]
    if: ${{
      github.event_name == 'schedule'
      || github.event_name == 'workflow_dispatch'
      || (github.event_name == 'push' && github.ref == 'refs/heads/main')
      || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'test-with-secrets'))
      }}
    uses: ./.github/workflows/rust-testing-integration.yaml
    secrets: inherit
    with:
      target: x86_64
      runner: ubuntu-latest

  # Code quality checks (runs independently)
  linting:
    name: Code Quality
    uses: ./.github/workflows/linting.yaml
