name: CI Coordinator

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:
  schedule:
    # Three times a day for integration tests
    - cron: '33 3,10,15 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # Essential builds for PR testing
  build_ubuntu:
    name: Build Ubuntu
    uses: ./.github/workflows/shared-build.yaml
    with:
      rust_channel: '1.89.0'
      upload_rust_artifacts: true
      upload_python_wheels: true
      target: x86_64
      runner: ubuntu-latest
      include_docker_setup: true

  build_macos_arm:
    name: Build macOS ARM
    uses: ./.github/workflows/shared-build.yaml
    with:
      rust_channel: '1.89.0'
      upload_rust_artifacts: true
      upload_python_wheels: true
      target: aarch64
      runner: macos-14
      include_docker_setup: false

  build_windows:
    name: Build Windows
    uses: ./.github/workflows/shared-build.yaml
    with:
      rust_channel: '1.89.0'
      upload_rust_artifacts: true
      upload_python_wheels: true
      target: x86_64
      runner: windows-latest
      include_docker_setup: false

  # Platform-specific tests
  test_ubuntu:
    name: Test Ubuntu
    needs: [build_ubuntu]
    uses: ./.github/workflows/rust-testing-safe.yaml
    with:
      target: x86_64
      runner: ubuntu-latest
      include_docker_tests: true

  test_macos_arm:
    name: Test macOS ARM
    needs: [build_macos_arm]
    uses: ./.github/workflows/rust-testing-safe.yaml
    with:
      target: aarch64
      runner: macos-14
      include_docker_tests: false

  test_windows:
    name: Test Windows
    needs: [build_windows]
    uses: ./.github/workflows/rust-testing-safe.yaml
    with:
      target: x86_64
      runner: windows-latest
      include_docker_tests: false

  # Python tests (using Ubuntu build)
  python_tests:
    name: Python Tests
    needs: [build_ubuntu]
    uses: ./.github/workflows/python-testing.yaml
    with:
      target: x86_64

  # Integration tests with cloud credentials
  test_integration:
    name: Test Integration
    needs: [build_ubuntu]
    if: ${{
      github.event_name == 'schedule'
      || github.event_name == 'workflow_dispatch'
      || (github.event_name == 'push' && github.ref == 'refs/heads/main')
      || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'test-with-secrets'))
      }}
    uses: ./.github/workflows/rust-testing-integration.yaml
    secrets: inherit
    with:
      target: x86_64
      runner: ubuntu-latest

  # Code quality checks (runs independently)
  linting:
    name: Code Quality
    uses: ./.github/workflows/linting.yaml
