name: Linting & Code Quality

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  RUST_CHANNEL: '1.89.0'

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Install system dependencies
      - name: Install Just
        run: sudo snap install --edge --classic just

      # Cache rustup toolchain installation
      - name: Cache rustup toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: rustup-${{ runner.os }}-${{ env.RUST_CHANNEL }}
          restore-keys: |
            rustup-${{ runner.os }}-

      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update ${{ env.RUST_CHANNEL }}
          rustup component add --toolchain ${{ env.RUST_CHANNEL }} rustfmt rust-src clippy
          rustup default ${{ env.RUST_CHANNEL }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      # Cache dependencies
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-${{ env.RUST_CHANNEL }}
          cache-all-crates: true
          cache-on-failure: true

      - name: Cache additional tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/codespell
            ~/.cache/actionlint
          key: tools-lint-${{ runner.os }}-${{ hashFiles('**/.pre-commit-config.yaml', '**/.codespellrc') }}
          restore-keys: |
            tools-lint-${{ runner.os }}-

      # Rust linting
      - name: Run Rust linting and formatting checks
        working-directory: ./icechunk
        run: just pre-commit-python

      # Python setup and linting
      - name: Setup Python linting environment
        working-directory: ./icechunk-python
        run: |
          uv sync --extra test
          uv add pre-commit

      - name: Run Python pre-commit linting
        working-directory: ./icechunk-python
        run: |
          SKIP=just-rust uv run pre-commit run --all-files

      - name: Run mypy type checking
        working-directory: ./icechunk-python
        run: |
          uv run mypy python

      # Spell checking
      - name: Annotate locations with typos
        uses: codespell-project/codespell-problem-matcher@v1.2.0

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2

      # GitHub Actions linting
      - name: Run actionlint
        uses: rhysd/actionlint@v1.7.7
        with:
          fail-on-error: true
