name: publish rust library

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  PIXI_VERSION: "v0.63.2"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    name: Check and publish
    runs-on: ubuntu-latest
    permissions:
       id-token: write  # needed to publish to crates.io

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Stand up docker services
        run: just contup

      - name: Wait for containers to be ready
        run: just contwait

      # TODO: not reusing cache to avoid a potentially poisoned one,
      #       but should be fine to reuse the one from main?
      #- name: Cache Dependencies
      #  uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2
      #  with:
      #    prefix-key: "rust-py314"
      #    shared-key: "rust"

      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          pixi-version: ${{ env.PIXI_VERSION }}
          cache: true
          activate-environment: true
          manifest-path: icechunk-python/pyproject.toml

      # FIXME: uncomment
      # - name: Check
      #   run: |
      #     just-pre-commit-ci

      - name: Setup git committer
        run: |
          git config --global user.email "joe@earthmover.io"
          git config --global user.name "Joe Hamman"

      - name: Publish workspace crates to crates.io
        run: just publish-crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
