name: Python Testing

on:
  workflow_call:
    inputs:
      rust_channel:
        description: 'Rust channel to use'
        required: false
        type: string
        default: '1.89.0'
      target:
        description: 'Target architecture (x86_64, aarch64)'
        required: false
        type: string
        default: 'x86_64'
      runner:
        description: 'GitHub runner to use'
        required: false
        type: string
        default: 'ubuntu-latest'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -W unreachable-pub -W bare-trait-objects"
  RUSTUP_MAX_RETRIES: 10

jobs:
  test:
    name: Python Tests
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        working-directory: ./icechunk-python
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Download pre-built Rust artifacts
      - name: Download Rust artifacts
        uses: actions/download-artifact@v4
        with:
          name: rust-artifacts-${{ inputs.target }}-${{ inputs.runner }}
          path: ./

      - name: Extract Rust artifacts
        run: |
          tar -xzf rust-target-${{ inputs.target }}-${{ inputs.runner }}.tar.gz
          rm rust-target-${{ inputs.target }}-${{ inputs.runner }}.tar.gz

      # Setup Docker services (only for Ubuntu)
      - name: Setup Docker services for testing
        if: ${{ runner.os == 'Linux' }}
        run: |
          docker compose up -d minio
          # Wait for MinIO
          for _ in {1..10}; do
              if curl --silent --fail http://minio:9000/minio/health/live; then
              break
              fi
              sleep 3
          done
          docker compose exec -T minio mc alias set minio http://minio:9000 minio123 minio123

      # Cache rustup toolchain installation
      - name: Cache rustup toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: rustup-${{ runner.os }}-${{ inputs.rust_channel }}
          restore-keys: |
            rustup-${{ runner.os }}-

      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update ${{ inputs.rust_channel }}
          rustup component add --toolchain ${{ inputs.rust_channel }} rustfmt rust-src clippy
          rustup default ${{ inputs.rust_channel }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ inputs.rust_channel }}-${{ inputs.target }}-${{ inputs.runner }}
          cache-all-crates: true
          cache-on-failure: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.local/share/uv/cache
            .venv
          key: python-test-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/requirements*.txt') }}
          restore-keys: |
            python-test-${{ runner.os }}-

      # Build wheel using pre-built Rust artifacts
      - name: Build Python wheel
        uses: PyO3/maturin-action@v1
        with:
          working-directory: icechunk-python
          target: ${{ inputs.target }}
          args: --release --out dist --find-interpreter

      # Install and test
      - name: Setup test environment
        run: |
          python -m venv .venv
          source .venv/bin/activate || .venv\\Scripts\\activate
          pip install --upgrade pip
          pip install dist/*.whl
          pip install pytest pytest-asyncio

      - name: Run Python tests
        run: |
          source .venv/bin/activate || .venv\\Scripts\\activate
          pytest python/
