name: Rust Testing (Safe)

on:
  workflow_call:
    inputs:
      target:
        description: 'Target architecture (x86_64, aarch64)'
        required: false
        type: string
        default: 'x86_64'
      runner:
        description: 'GitHub runner to use'
        required: false
        type: string
        default: 'ubuntu-latest'
      include_docker_tests:
        description: 'Whether to include Docker-based tests'
        required: false
        type: boolean
        default: false
      rust_channel:
        description: 'Rust channel to use'
        required: false
        type: string
        default: '1.89.0'

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -W unreachable-pub -W bare-trait-objects"
  RUSTUP_MAX_RETRIES: 10
  RUST_CHANNEL: ${{ inputs.rust_channel }}
  CARGO_DENY_VERSION: '0.18.4'

jobs:
  test:
    name: Safe Rust Tests (${{ inputs.target }})
    runs-on: ${{ inputs.runner }}
    # Safe for all contributors (no cloud credentials)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Download artifacts built by shared-build
      - name: Download Rust artifacts
        uses: actions/download-artifact@v4
        with:
          name: rust-artifacts-${{ inputs.target }}-${{ inputs.runner }}
          path: ./

      - name: Extract Rust artifacts
        run: |
          tar -xzf rust-target-${{ inputs.target }}-${{ inputs.runner }}.tar.gz
          rm rust-target-${{ inputs.target }}-${{ inputs.runner }}.tar.gz

      - name: Install Just
        if: ${{ inputs.include_docker_tests }}
        run: sudo snap install --edge --classic just

      # Cache rustup toolchain installation
      - name: Cache rustup toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: rustup-${{ runner.os }}-${{ inputs.rust_channel }}
          restore-keys: |
            rustup-${{ runner.os }}-

      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update ${{ inputs.rust_channel }}
          rustup component add --toolchain ${{ inputs.rust_channel }} rustfmt rust-src clippy
          rustup default ${{ inputs.rust_channel }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ inputs.rust_channel }}-${{ inputs.target }}-${{ inputs.runner }}
          cache-all-crates: true
          cache-on-failure: true

      # Run safe tests with Docker (excludes cloud integration tests)
      # Note: Docker services are set up in separate job that runs in parallel with builds
      - name: Run safe tests with Docker
        if: ${{ inputs.include_docker_tests }}
        run: |
          just compile-tests "--locked"
          just build
          just format "--check"
          just lint "-p icechunk -p icechunk-python"
          just doctest
          just test-safe
          just run-all-examples

      # Run unit tests only (if no Docker)
      - name: Run unit tests
        if: ${{ !inputs.include_docker_tests }}
        run: cargo test --lib
