name: Shared Build Infrastructure

on:
  workflow_call:
    inputs:
      rust_channel:
        description: 'Rust channel to use'
        required: false
        type: string
        default: '1.89.0'
      upload_rust_artifacts:
        description: 'Whether to upload Rust build artifacts'
        required: false
        type: boolean
        default: false
      target:
        description: 'Build target architecture (x86_64, aarch64)'
        required: false
        type: string
        default: 'x86_64'
      runner:
        description: 'GitHub runner to use'
        required: false
        type: string
        default: 'ubuntu-latest'
      include_docker_setup:
        description: 'Whether to set up Docker infrastructure (only needed for Ubuntu)'
        required: false
        type: boolean
        default: false
    outputs:
      rust_cache_hit:
        description: "Whether Rust cache was hit"
        value: ${{ jobs.build.outputs.cache_hit }}

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -W unreachable-pub -W bare-trait-objects"
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    name: Build & Test Setup
    runs-on: ${{ inputs.runner }}
    outputs:
      cache_hit: ${{ steps.rust_cache.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Start Docker services early (non-blocking, only for Ubuntu)
      - name: Start Docker services in background
        if: ${{ inputs.include_docker_setup }}
        run: |
          docker compose up -d

      # Install Rust while Docker starts up
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update ${{ inputs.rust_channel }}
          rustup component add --toolchain ${{ inputs.rust_channel }} rustfmt rust-src clippy
          rustup default ${{ inputs.rust_channel }}

      - name: Cache Rust dependencies and build artifacts
        id: rust_cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os == 'Windows' && 'windows' || runner.os == 'macOS' && 'macos' || 'ubuntu' }}-${{ inputs.rust_channel }}
          cache-directories: |
            ~/.cargo/bin/
            target/
          cache-all-crates: true
          cache-on-failure: true

      # Build Rust while Docker continues starting
      - name: Build Rust project
        run: |
          cargo build --release --target-dir target

      # Only wait for Docker after Rust build is done (for Ubuntu)
      - name: Ensure Docker services are ready
        if: ${{ inputs.include_docker_setup }}
        run: |
          # Wait for MinIO
          for _ in {1..10}; do
              if curl --silent --fail http://minio:9000/minio/health/live; then
              break
              fi
              sleep 3
          done
          docker compose exec -T minio mc alias set minio http://minio:9000 minio123 minio123

          # Wait for Azurite
          for _ in {1..20}; do
              if curl --silent --fail "http://azurite:10000/devstoreaccount1/testcontainer?sv=2023-01-03&ss=btqf&srt=sco&spr=https%2Chttp&st=2025-01-06T14%3A53%3A30Z&se=2035-01-07T14%3A53%3A00Z&sp=rwdftlacup&sig=jclETGilOzONYp4Y0iK9SpVRLGyehaS5lg5booJ9VYA%3D&restype=container"; then
              break
              fi
              sleep 3
          done

      - name: Compress Rust build artifacts
        if: ${{ inputs.upload_rust_artifacts }}
        run: |
          tar -czf rust-target-${{ inputs.target }}-${{ inputs.runner }}.tar.gz target/

      - name: Upload Rust build artifacts
        if: ${{ inputs.upload_rust_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: rust-artifacts-${{ inputs.target }}-${{ inputs.runner }}
          path: rust-target-${{ inputs.target }}-${{ inputs.runner }}.tar.gz
          retention-days: 1
