name: Windows tests
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  merge_group:
  push:
    branches:
      - main
      - 'support/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10
  PIXI_VERSION: "v0.63.2"

jobs:
  rust:
    name: Run rust tests in windows
    timeout-minutes: 20
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2
        with:
          add-job-id-key: "false"

      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          pixi-version: ${{ env.PIXI_VERSION }}
          cache: true
          activate-environment: true
          manifest-path: icechunk-python/pyproject.toml

      - name: Run tests
        run: |
          just profile=ci unit-test
